#!/bin/bash

for((idx=0; idx<5; idx++)) ; do
  /sbin/service %{_tomcat} stop
  if [ $? == 0 ] ; then idx=5; else sleep 5; fi
done

# Remove the axis1-based installation 
if [ -f /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/server-config.wsdd ] ; then
  rm -rf /var/lib/%{_tomcat}/webapps/ce-cream
  rm -f /etc/%{_tomcat}/Catalina/localhost/ce-cream.xml
  rm -rf /var/cache/%{_tomcat}/work/Catalina/localhost/ce-cream
fi

