#!/bin/bash

# Do not overwrite axis2-based installation
if [ ! -L /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/services/glite-ce-cream.aar ] ; then

  cp -R /usr/share/axis2/webapp /var/lib/%{_tomcat}/webapps/ce-cream || exit 1
  
  ln -s /usr/share/java/jclassads/cedar.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/jclassads/classad.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/argus-pep-api-java-compat.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/argus-pep-common-compat.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/bcprov.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/canl.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-common-java.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-cream-api-java.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-cream-blahExecutor.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-cream-core.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-cream-delegationExecutor.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-cream-skeleton.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-delegation-skeleton.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/glite-jdl-api-java.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib
  ln -s /usr/share/java/voms-api-java.jar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/lib

%if 0%{?el6}
  # set allowLinking option for tomcat6
  mkdir /var/lib/%{_tomcat}/webapps/ce-cream/META-INF
  echo '<Context override="true" allowLinking="true"></Context>' > /var/lib/%{_tomcat}/webapps/ce-cream/META-INF/context.xml
%endif

  ln -s /usr/share/glite-ce-cream/modules/glite-ce-cream-authorization.mar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/modules
  find /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/modules -name *.mar -exec basename \\{\\} \\; > /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/modules/modules.list
  
  ln -s /usr/share/glite-ce-cream/services/glite-ce-cream.aar /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/services
  find /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/services -name *.aar -exec basename \\{\\} \\; >  /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/services/services.list

  cp /etc/glite-ce-dbtool/creamdb_min_access.conf.template /etc/glite-ce-cream/creamdb_min_access.conf
  
fi

# Axis Servlet configuration
# customization of axis2.xml
REPLACE1='s|__CHANGE_SERVICE__|/etc/glite-ce-cream/cream-config.xml|g'
REPLACE2='s|__CHANGE_LOG4J__|/etc/glite-ce-cream/log4j.properties|g'
  
sed "$REPLACE1 ; $REPLACE2 " /etc/glite-ce-common-java/axis2.xml > /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/conf/axis2.xml
chmod 600 /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/conf/axis2.xml
chown tomcat.tomcat /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/conf/axis2.xml
# cannot use symlinks for the following files:
cp -f /etc/glite-ce-common-java/web.xml /var/lib/%{_tomcat}/webapps/ce-cream/WEB-INF/


if [ $1 -eq 1 ] ; then

  #
  # Installation workarounds
  #
  mkdir -p /var/cream
  chown tomcat:tomcat /var/cream
  chmod 700 /var/cream

  mkdir -p /var/cream_sandbox
  chown tomcat:tomcat /var/cream_sandbox
  chmod 700 /var/cream_sandbox

  mkdir -p /var/log/cream
  chown tomcat:tomcat /var/log/cream
  chmod 755 /var/log/cream
    
  mkdir -p /var/log/cream/accounting
  chown root.tomcat /var/log/cream/accounting
  chmod 0730 /var/log/cream/accounting
        
  chown tomcat.tomcat /var/blah
  chmod 771 /var/blah

  chown tomcat.tomcat /usr/bin/glite_cream_load_monitor
  
  /sbin/service %{_tomcat} start
  
fi

